name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit-tests:
    name: Unit Tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: 'jdk'
      
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Run Linter
        run: ./gradlew lint

      - name: Run Unit Tests
        run: ./gradlew test

  android-tests:
    name: Android Tests
    runs-on: [macos-latest]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: 'jdk'

      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

